# Generated by Django 6.0.1 on 2026-02-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('post', 'Created Post'), ('comment', 'Commented'), ('like', 'Liked Post')], max_length=20),
        ),
    ]
